# Generated by Django 5.2.7 on 2025-12-02 06:26

import ckeditor_uploader.fields
import django.core.validators
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='banner/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION])),
                ('title', models.CharField(blank=True, help_text='Enter your banner title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your banner description...', null=True, verbose_name='Description')),
                ('secure_business_btn_name', models.CharField(blank=True, help_text='Enter secure my business button name...', max_length=180, null=True, verbose_name='Secure My Business Button Name')),
                ('secure_business_btn_url', models.URLField(blank=True, help_text='Enter secure my business button URL...', max_length=180, null=True, verbose_name='Secure My Business Button URL')),
                ('company_profile_btn_name', models.CharField(blank=True, help_text='Enter company profile button name...', max_length=180, null=True, verbose_name='Company Profile Button Name')),
                ('company_profile_btn_url', models.URLField(blank=True, help_text='Enter company profile button URL...', max_length=180, null=True, verbose_name='Company Profile Button URL')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='CybersecuritySolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Upload cyber security item image...', null=True, upload_to='cybers-ecurity/', verbose_name='Cyber Security Item Image')),
                ('title', models.CharField(blank=True, help_text='Enter cyber security item title...', max_length=280, null=True, verbose_name='Cyber Security Item Title')),
                ('count', models.IntegerField(default=0, help_text='Enter cyber security item count...', verbose_name='Cyber Security Item Count')),
            ],
            options={
                'verbose_name': 'Cybersecurity Excellence Items',
                'verbose_name_plural': 'Cybersecurity Excellence Items',
            },
        ),
        migrations.CreateModel(
            name='CybersecuritySolutionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Cyber Security Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Cyber Security Description')),
                ('image', models.FileField(blank=True, null=True, upload_to='cyber-ecurity/', verbose_name='Cyber Security Image')),
            ],
            options={
                'verbose_name': 'Cybersecurity Excellence Title',
                'verbose_name_plural': 'Cybersecurity Excellence Title',
            },
        ),
        migrations.CreateModel(
            name='ExperienceEic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Experience Eic item normal title')),
                ('span_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='ExperienceEic item span title')),
                ('image', models.FileField(blank=True, null=True, upload_to='experience-eic/', verbose_name='Image')),
                ('btn_name', models.CharField(blank=True, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Experience Top Bar',
                'verbose_name_plural': 'Experience Top Bar',
            },
        ),
        migrations.CreateModel(
            name='ExperienceEicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Item Name')),
            ],
            options={
                'verbose_name': 'Experience Impact Items',
                'verbose_name_plural': 'Experience Impact Items',
            },
        ),
        migrations.CreateModel(
            name='GloballyAccredited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('bg', models.FileField(blank=True, null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Globally Accredited',
                'verbose_name_plural': 'Globally Accredited',
            },
        ),
        migrations.CreateModel(
            name='OurProvenProcessSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security image')),
                ('title_before_span', models.CharField(blank=True, help_text='Enter your our proven process security before span...', max_length=280, null=True, verbose_name='our proven process security title before span')),
                ('title_span', models.CharField(blank=True, help_text='Enter your our proven process security title span...', max_length=280, null=True, verbose_name='our proven process security title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Enter your our proven process security title after span...', max_length=280, null=True, verbose_name='our proven process security title after span')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security description')),
            ],
            options={
                'verbose_name': 'Proven Process Security',
                'verbose_name_plural': 'Proven Process Security',
            },
        ),
        migrations.CreateModel(
            name='OurProvenProcessSecurityItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security item image')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='our proven process security item title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security item description')),
            ],
            options={
                'verbose_name': 'Proven Process Security Items',
                'verbose_name_plural': 'Proven Process Security Items',
            },
        ),
        migrations.CreateModel(
            name='PaymnetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Payment logo', null=True, upload_to='paymnets/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('btn_name', models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.FileField(blank=True, help_text='Upload review author image...', null=True, upload_to='reviews', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Author Image')),
                ('author_name', models.CharField(blank=True, help_text='Enter review author name...', max_length=180, null=True, verbose_name='Author Name')),
                ('author_bio', models.CharField(blank=True, help_text='Enter review author bio...', max_length=280, null=True, verbose_name='Author Bio')),
                ('content', models.TextField(blank=True, help_text='Enter review content...', null=True, verbose_name='Review Content')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, help_text='Enter your review top bar before span...', max_length=280, null=True, verbose_name='Review top bar title before span')),
                ('title_span', models.CharField(blank=True, help_text='Enter your review top bar title span...', max_length=280, null=True, verbose_name='Review top bar title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Enter your review top bar title after span...', max_length=280, null=True, verbose_name='Review top bar title after span')),
            ],
            options={
                'verbose_name': 'Review Top Bar',
                'verbose_name_plural': 'Review Top Bar',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context')),
                ('type', models.CharField(default='HomePage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name')),
                ('url', models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('logo', models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Schema',
                'verbose_name_plural': 'SEO Schema',
            },
        ),
        migrations.CreateModel(
            name='SecurityFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(blank=True, help_text='Upload your security firm bg image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Security Firm BG')),
                ('main_img', models.FileField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Main Image')),
                ('sub_img', models.FileField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Sub Image')),
                ('title_span', models.CharField(blank=True, help_text='This part will be wrapped in <span> in frontend', max_length=280, null=True, verbose_name='Title (span part)')),
                ('title_normal', models.CharField(blank=True, help_text='This part will be outside <span> in frontend', max_length=280, null=True, verbose_name='Title (normal part)')),
                ('mission_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Mission Title')),
                ('mission_description', models.TextField(blank=True, null=True, verbose_name='Mission description')),
                ('vision_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Vision Title')),
                ('vision_description', models.TextField(blank=True, null=True, verbose_name='Vision description')),
                ('get_to_know_us_btn_name', models.CharField(blank=True, help_text='Enter get to know us button name...', max_length=180, null=True, verbose_name='Get To Know Us Button Name')),
                ('get_to_know_us_btn_url', models.URLField(blank=True, help_text='Enter get to know us button URL...', max_length=180, null=True, verbose_name='Get To Know Us Button URL')),
                ('security_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Security Persentences')),
                ('response_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Response Persentences')),
                ('compliance_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Compliance Persentences')),
            ],
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('author', models.CharField(max_length=280, verbose_name='Author Name')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tag',
            },
        ),
    ]