# Generated by Django 5.2.7 on 2025-11-29 05:35

import django.core.validators
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='banner/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION])),
                ('title', models.CharField(blank=True, help_text='Enter your banner title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your banner description...', null=True, verbose_name='Description')),
                ('secure_business_btn_name', models.CharField(blank=True, help_text='Enter secure my business button name...', max_length=180, null=True, verbose_name='Secure My Business Button Name')),
                ('secure_business_btn_url', models.URLField(blank=True, help_text='Enter secure my business button URL...', max_length=180, null=True, verbose_name='Secure My Business Button URL')),
                ('company_profile_btn_name', models.CharField(blank=True, help_text='Enter company profile button name...', max_length=180, null=True, verbose_name='Company Profile Button Name')),
                ('company_profile_btn_url', models.URLField(blank=True, help_text='Enter company profile button URL...', max_length=180, null=True, verbose_name='Company Profile Button URL')),
            ],
        ),
        migrations.CreateModel(
            name='CybersecuritySolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Upload cyber security solution item image...', null=True, upload_to='cybers-ecurity/', verbose_name='Cyber Security Solution Item Image')),
                ('title', models.CharField(blank=True, help_text='Enter cyber security solution item title...', max_length=280, null=True, verbose_name='Cyber Security Solution Item Title')),
                ('count', models.IntegerField(default=0, help_text='Enter cyber security solution item count...', verbose_name='Cyber Security Solution Item Count')),
            ],
        ),
        migrations.CreateModel(
            name='CybersecuritySolutionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Cyber Security Solution Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Cyber Security Solution Description')),
                ('image', models.FileField(blank=True, null=True, upload_to='cyber-ecurity/', verbose_name='Cyber Security Solution Image')),
            ],
        ),
        migrations.CreateModel(
            name='OurProvenProcessSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security image')),
                ('title_before_span', models.CharField(blank=True, help_text='Enter your our proven process security before span...', max_length=280, null=True, verbose_name='our proven process security title before span')),
                ('title_span', models.CharField(blank=True, help_text='Enter your our proven process security title span...', max_length=280, null=True, verbose_name='our proven process security title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Enter your our proven process security title after span...', max_length=280, null=True, verbose_name='our proven process security title after span')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security description')),
            ],
        ),
        migrations.CreateModel(
            name='OurProvenProcessSecurityItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='our-proven-process-security/', verbose_name='our proven process security item image')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='our proven process security item title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='our proven process security item description')),
            ],
        ),
        migrations.CreateModel(
            name='PaymnetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Payment logo', null=True, upload_to='paymnets/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('description', models.TextField(verbose_name='Description')),
                ('btn_url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.FileField(blank=True, help_text='Upload review author image...', null=True, upload_to='reviews', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Author Image')),
                ('author_name', models.CharField(blank=True, help_text='Enter review author name...', max_length=180, null=True, verbose_name='Author Name')),
                ('author_bio', models.CharField(blank=True, help_text='Enter review author bio...', max_length=280, null=True, verbose_name='Author Bio')),
                ('content', models.TextField(blank=True, help_text='Enter review content...', null=True, verbose_name='Review Content')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, help_text='Enter your review top bar before span...', max_length=280, null=True, verbose_name='Review top bar title before span')),
                ('title_span', models.CharField(blank=True, help_text='Enter your review top bar title span...', max_length=280, null=True, verbose_name='Review top bar title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Enter your review top bar title after span...', max_length=280, null=True, verbose_name='Review top bar title after span')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(blank=True, help_text='Upload your security firm bg image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Security Firm BG')),
                ('main_img', models.FileField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Main Image')),
                ('sub_img', models.FileField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Sub Image')),
                ('title_span', models.CharField(blank=True, help_text='This part will be wrapped in <span> in frontend', max_length=280, null=True, verbose_name='Title (span part)')),
                ('title_normal', models.CharField(blank=True, help_text='This part will be outside <span> in frontend', max_length=280, null=True, verbose_name='Title (normal part)')),
                ('mission_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Mission Title')),
                ('mission_description', models.TextField(blank=True, null=True, verbose_name='Mission description')),
                ('vision_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Vision Title')),
                ('vision_description', models.TextField(blank=True, null=True, verbose_name='Vision description')),
                ('get_to_know_us_btn_name', models.CharField(blank=True, help_text='Enter get to know us button name...', max_length=180, null=True, verbose_name='Get To Know Us Button Name')),
                ('get_to_know_us_btn_url', models.URLField(blank=True, help_text='Enter get to know us button URL...', max_length=180, null=True, verbose_name='Get To Know Us Button URL')),
                ('security_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Security Persentences')),
                ('response_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Response Persentences')),
                ('compliance_persentences', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Compliance Persentences')),
            ],
        ),
    ]
