# Generated by Django 5.2.7 on 2025-12-02 06:09

import ckeditor_uploader.fields
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceEic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Experience Eic item normal title')),
                ('span_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='ExperienceEic item span title')),
                ('image', models.FileField(blank=True, null=True, upload_to='experience-eic/', verbose_name='Image')),
                ('btn_name', models.CharField(blank=True, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Experience Top Bar',
                'verbose_name_plural': 'Experience Top Bar',
            },
        ),
        migrations.CreateModel(
            name='ExperienceEicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Item Name')),
            ],
            options={
                'verbose_name': 'Experience Impact Items',
                'verbose_name_plural': 'Experience Impact Items',
            },
        ),
        migrations.CreateModel(
            name='GloballyAccredited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('bg', models.FileField(blank=True, null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Background Image')),
            ],
            options={
                'verbose_name': 'Globally Accredited',
                'verbose_name_plural': 'Globally Accredited',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context')),
                ('type', models.CharField(default='HomePage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name')),
                ('url', models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('logo', models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Schema',
                'verbose_name_plural': 'SEO Schema',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('author', models.CharField(max_length=280, verbose_name='Author Name')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tag',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='cybersecuritysolutionitem',
            options={'verbose_name': 'Cybersecurity Excellence Items', 'verbose_name_plural': 'Cybersecurity Excellence Items'},
        ),
        migrations.AlterModelOptions(
            name='cybersecuritysolutiontitle',
            options={'verbose_name': 'Cybersecurity Excellence Title', 'verbose_name_plural': 'Cybersecurity Excellence Title'},
        ),
        migrations.AlterModelOptions(
            name='ourprovenprocesssecurity',
            options={'verbose_name': 'Proven Process Security', 'verbose_name_plural': 'Proven Process Security'},
        ),
        migrations.AlterModelOptions(
            name='ourprovenprocesssecurityitems',
            options={'verbose_name': 'Proven Process Security Items', 'verbose_name_plural': 'Proven Process Security Items'},
        ),
        migrations.AlterModelOptions(
            name='paymnetinfo',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewtopbar',
            options={'verbose_name': 'Review Top Bar', 'verbose_name_plural': 'Review Top Bar'},
        ),
        migrations.AddField(
            model_name='paymnetinfo',
            name='btn_name',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutionitem',
            name='count',
            field=models.IntegerField(default=0, help_text='Enter cyber security item count...', verbose_name='Cyber Security Item Count'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutionitem',
            name='image',
            field=models.FileField(blank=True, help_text='Upload cyber security item image...', null=True, upload_to='cybers-ecurity/', verbose_name='Cyber Security Item Image'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutionitem',
            name='title',
            field=models.CharField(blank=True, help_text='Enter cyber security item title...', max_length=280, null=True, verbose_name='Cyber Security Item Title'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutiontitle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Cyber Security Description'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutiontitle',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cyber-ecurity/', verbose_name='Cyber Security Image'),
        ),
        migrations.AlterField(
            model_name='cybersecuritysolutiontitle',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Cyber Security Title'),
        ),
        migrations.AlterField(
            model_name='paymnetinfo',
            name='btn_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='paymnetinfo',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
