# Generated by Django 5.2.7 on 2026-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seotag',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='author',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='title',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
