# Generated by Django 6.0.1 on 2026-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_seotag_canonical_url_seotag_category_seotag_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='homepage_schema',
        ),
        migrations.DeleteModel(
            name='SeoTag',
        ),
        migrations.AddField(
            model_name='banner',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='cybersecuritysolutiontitle',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='paymnetinfo',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='securityfirm',
            name='main_img_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Main Image Alt Text'),
        ),
        migrations.AddField(
            model_name='securityfirm',
            name='sub_img_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Sub Image Alt Text'),
        ),
        migrations.DeleteModel(
            name='HomePageSchema',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
