# Generated by Django 6.0.1 on 2026-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_organization_homepage_schema_delete_seotag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersecuritysolutionitem',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='experienceeic',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='globallyaccredited',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='ourprovenprocesssecurity',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='ourprovenprocesssecurityitems',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
    ]
