# Generated by Django 5.2.7 on 2025-11-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_ourprovenprocesssecurity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='CybersecuritySolutionItem',
        ),
        migrations.DeleteModel(
            name='CybersecuritySolutionTitle',
        ),
        migrations.DeleteModel(
            name='OurProvenProcessSecurity',
        ),
        migrations.DeleteModel(
            name='OurProvenProcessSecurityItems',
        ),
        migrations.DeleteModel(
            name='SecurityFirm',
        ),
    ]
