# Generated by Django 5.2.7 on 2025-12-02 06:26

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your about section top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your about section top bar description...', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About Top Bar',
                'verbose_name_plural': 'About Top Bar',
            },
        ),
        migrations.CreateModel(
            name='DigitalSecuritySolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(blank=True, null=True, verbose_name='Count')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Digital Security Solution Items',
                'verbose_name_plural': 'Digital Security Solution Items',
            },
        ),
        migrations.CreateModel(
            name='DigitalSecuritySolutionTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=380, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Digital Security Solution Top Bar',
                'verbose_name_plural': 'Digital Security Solution Top Bar',
            },
        ),
        migrations.CreateModel(
            name='HappyJourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('title', models.CharField(blank=True, max_length=380, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Happy Journey Items',
                'verbose_name_plural': 'Happy Journey Items',
            },
        ),
        migrations.CreateModel(
            name='HappyJourneyTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Happy Journey Top Bar',
                'verbose_name_plural': 'Happy Journey Top Bar',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context')),
                ('type', models.CharField(default='AboutPage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name')),
                ('url', models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('logo', models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Schema',
                'verbose_name_plural': 'SEO Schema',
            },
        ),
        migrations.CreateModel(
            name='SecureFutureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='secure-future/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Secure Future Items',
                'verbose_name_plural': 'Secure Future Items',
            },
        ),
        migrations.CreateModel(
            name='SecureFutureTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Normal Title')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
            ],
            options={
                'verbose_name': 'Secure Future Top Bar',
                'verbose_name_plural': 'Secure Future Top Bar',
            },
        ),
        migrations.CreateModel(
            name='SecurityFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(blank=True, help_text='Upload your security firm bg image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Security Firm BG')),
                ('main_img', models.FileField(blank=True, help_text='Upload your security firm image...', null=True, upload_to='security-firm/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Main Image')),
                ('title_span', models.CharField(blank=True, help_text='This part will be wrapped in <span> in frontend', max_length=280, null=True, verbose_name='Title (span part)')),
                ('title_normal', models.CharField(blank=True, help_text='This part will be outside <span> in frontend', max_length=280, null=True, verbose_name='Title (normal part)')),
                ('mission_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Mission Title')),
                ('mission_description', models.TextField(blank=True, null=True, verbose_name='Mission description')),
                ('vision_title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Vision Title')),
                ('vision_description', models.TextField(blank=True, null=True, verbose_name='Vision description')),
                ('get_to_know_us_btn_name', models.CharField(blank=True, help_text='Enter get to know us button name...', max_length=180, null=True, verbose_name='Get To Know Us Button Name')),
                ('get_to_know_us_btn_url', models.URLField(blank=True, help_text='Enter get to know us button URL...', max_length=180, null=True, verbose_name='Get To Know Us Button URL')),
            ],
            options={
                'verbose_name': 'Security Firm',
                'verbose_name_plural': 'Security Firm',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tag',
            },
        ),
    ]
