# Generated by Django 5.2.7 on 2026-01-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0002_aboutpageschema_organization_delete_schema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='homepage_schema',
            new_name='aboutpage_schema',
        ),
    ]
