# Generated by Django 6.0.1 on 2026-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0003_rename_homepage_schema_organization_aboutpage_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='aboutpage_schema',
        ),
        migrations.DeleteModel(
            name='SeoTag',
        ),
        migrations.AddField(
            model_name='securefutureitem',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='securityfirm',
            name='bg_image_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='BG Image Alt'),
        ),
        migrations.AddField(
            model_name='securityfirm',
            name='main_image_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Main Image Alt'),
        ),
        migrations.AlterField(
            model_name='securefutureitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='secure-future/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='securefutureitem',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='AboutPageSchema',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
