# Generated by Django 6.0.1 on 2026-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0004_remove_organization_aboutpage_schema_delete_seotag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsecuritysolutiontopbar',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='happyjourneyitem',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
    ]
