# Generated by Django 6.0.1 on 2026-02-02 10:08

import ckeditor_uploader.fields
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter your blog section top bar title...', max_length=280, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your blog section top bar description...', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Blog Top Bar',
                'verbose_name_plural': 'Blog Top Bar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter tag name...', max_length=255, unique=True, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Upload your blog image...', null=True, upload_to='blogs', verbose_name='Image')),
                ('blog_image_alt', models.CharField(blank=True, max_length=280, null=True, verbose_name='Blog Image Alt')),
                ('title', models.CharField(help_text='Enter your blog title...', max_length=280, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter your blog content...', null=True, verbose_name='Content')),
                ('author_image', models.FileField(blank=True, help_text='Upload blog author image...', null=True, upload_to='blogs/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Author Image')),
                ('author_image_alt', models.CharField(blank=True, max_length=280, null=True, verbose_name='Author Image Alt')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_bio', models.CharField(blank=True, max_length=280, null=True)),
                ('author_description', models.TextField(blank=True, null=True)),
                ('author_facebook_url', models.URLField(blank=True, null=True)),
                ('author_twitter_url', models.URLField(blank=True, null=True)),
                ('author_medium_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blogs.tag', verbose_name='Tag')),
            ],
        ),
    ]
