# Generated by Django 5.2.7 on 2025-11-17 12:59

import ckeditor_uploader.fields
import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter tag name...', max_length=255, unique=True, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your blog image...', null=True, upload_to='blogs', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your blog title...', max_length=500, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter your blog content...', verbose_name='Content')),
                ('author_name', models.CharField(max_length=255)),
                ('author_bio', models.CharField(max_length=500)),
                ('author_description', models.TextField()),
                ('author_facebook_url', models.URLField(blank=True, null=True)),
                ('author_twitter_url', models.URLField(blank=True, null=True)),
                ('author_medium_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blogs.tag')),
            ],
        ),
    ]
