# Generated by Django 5.2.7 on 2025-11-17 13:15

import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, help_text='Upload blog author image...', null=True, upload_to='blogs/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Author Image'),
        ),
    ]
