# Generated by Django 6.0.1 on 2026-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='SeoTag',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='og_image_file',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='schema_context',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='schema_custom_json',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='schema_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='twitter_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='twitter_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='twitter_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Author Image Alt'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image_alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Blog Image Alt'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your blog image...', null=True, upload_to='blogs', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
