# Generated by Django 6.0.1 on 2026-02-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_delete_schema_delete_seotag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_bio',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter your blog title...', max_length=280, unique=True, verbose_name='Title'),
        ),
    ]
