# Generated by Django 5.2.7 on 2025-11-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_author_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your blog section top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your blog section top bar description...', verbose_name='Description')),
            ],
        ),
    ]
