# Generated by Django 5.2.7 on 2025-11-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogtopbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtopbar',
            options={'verbose_name': 'Blog Top Bar', 'verbose_name_plural': 'Blog Top Bar'},
        ),
    ]
