# Generated by Django 5.2.7 on 2025-11-24 13:12

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogtopbar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_image',
            field=models.FileField(blank=True, help_text='Upload blog author image...', null=True, upload_to='blogs/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Author Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your blog image...', null=True, upload_to='blogs', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
