# Generated by Django 5.2.7 on 2025-12-02 06:09

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_author_bio_alter_blog_author_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'verbose_name': 'SEO Schema', 'verbose_name_plural': 'SEO Schema'},
        ),
        migrations.AlterModelOptions(
            name='seotag',
            options={'verbose_name': 'SEO Tag', 'verbose_name_plural': 'SEO Tag'},
        ),
        migrations.AddField(
            model_name='blog',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for Open Graph.', null=True, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_image',
            field=models.URLField(blank=True, help_text='Full URL of image for OG (optional).', null=True, verbose_name='OG Image URL'),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_image_file',
            field=models.ImageField(blank=True, help_text='Upload OG image for this blog. If set, this will be used.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File'),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for Facebook / LinkedIn when this blog is shared.', max_length=255, null=True, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='og_type',
            field=models.CharField(default='article', help_text='Type of Open Graph object, e.g., article.', max_length=50, verbose_name='OG Type'),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema_context',
            field=models.CharField(blank=True, default='https://schema.org', help_text='Usually https://schema.org', max_length=280, null=True, verbose_name='Schema Context'),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema_custom_json',
            field=models.TextField(blank=True, help_text='Optional: paste full JSON-LD here to override auto-generated schema.', null=True, verbose_name='Custom Schema JSON'),
        ),
        migrations.AddField(
            model_name='blog',
            name='schema_type',
            field=models.CharField(blank=True, default='BlogPosting', help_text='JSON-LD @type, e.g., BlogPosting, Article, NewsArticle.', max_length=50, null=True, verbose_name='Schema Type'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Short description for this blog (SEO meta description).', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords for this blog.', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom title for this blog detail page (for browser tab & search engines).', max_length=380, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Description for Twitter card.', null=True, verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_image',
            field=models.URLField(blank=True, help_text='Image URL for Twitter card preview.', null=True, verbose_name='Twitter Image URL'),
        ),
        migrations.AddField(
            model_name='blog',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Title for Twitter card.', max_length=255, null=True, verbose_name='Twitter Title'),
        ),
        migrations.AddField(
            model_name='schema',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='schema',
            name='logo',
            field=models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_image_file',
            field=models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blogs.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='blogtopbar',
            name='description',
            field=models.TextField(blank=True, help_text='Enter your blog section top bar description...', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blogtopbar',
            name='title',
            field=models.CharField(blank=True, help_text='Enter your blog section top bar title...', max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='contact_type',
            field=models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='context',
            field=models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='description',
            field=models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='url',
            field=models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title'),
        ),
    ]
