#############################################################################
######### DJANGO REST FRAMEWORK DEVELOPMENT DOCKERFILE CONFIGURATION ########
#############################################################################

# PYTHON 3.12 SLIM IMAGE
FROM python:3.12-slim

# WORKING DIR
WORKDIR /app

# UPGRADE SYSTEM && NEED PACKENGS
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        gcc python3-dev libjpeg-dev zlib1g-dev default-libmysqlclient-dev pkg-config netcat-openbsd curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# COPY REQUIREMENTS.TXT
COPY requirements/dev.txt ./requirements/dev.txt

# REQUIREMENTS.TXT ALL PACKENGS INSTALL
RUN pip install --upgrade pip && \
    pip install -r ./requirements/dev.txt && \
    pip install python-dotenv daphne redis

# COPY APPLICATION CODE
COPY . .

# EXPOSE PORT
EXPOSE 8000

# START 
CMD ["sh", "./entrypoint.sh"]
