import { getFetchData } from "@/utils/getFetchData";
import { Metadata } from "next";

const fetchSeoTag = async () => {
  const res = await getFetchData('/services/seo-tag/');
  return res?.data || null;
};

export async function generateMetadata(): Promise<Metadata> {
  const seo = await fetchSeoTag();

  return {
    // Basic Meta
    title: seo?.title || "Eic - Services Page",
    description: seo?.description || "Generated by create next app",
    keywords: seo?.keywords || "cybersecurity, eic",
    authors: seo?.author ? [{ name: seo.author }] : [],
    category: seo?.category || undefined,

    // Canonical
    alternates: {
      canonical: seo?.canonical_url || "https://eic.com.bd/services",
    },

    // Open Graph
    openGraph: {
      title: seo?.og_title || seo?.title,
      description: seo?.og_description || seo?.description,
      url: seo?.og_url || seo?.canonical_url,
      type: seo?.og_type || "website",
      siteName: seo?.og_site_name || "EIC",
      locale: seo?.og_locale || "en_US",
      images: seo?.og_image ? [{ url: seo.og_image }] : [],
    },

    // Twitter
    twitter: {
      card: seo?.twitter_card || "summary_large_image",
      title: seo?.twitter_title || seo?.title,
      description: seo?.twitter_description || seo?.description,
      images: seo?.twitter_image ? [seo.twitter_image] : [],
      site: seo?.twitter_site || "",
      creator: seo?.twitter_creator || "",
    },

    metadataBase: new URL(seo?.canonical_url || "https://eic.com.bd/services"),
    other: {
      "creator": seo?.creator || undefined,
      "article:published_time": seo?.published_time || undefined,
      "article:modified_time": seo?.modified_time || undefined,
    },

  };
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            {children}
        </main>
    );
}
