# Generated by Django 5.2.7 on 2025-12-02 06:26

import django.core.validators
import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Compliance Items',
                'verbose_name_plural': 'Compliance Items',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('btn_name', models.CharField(max_length=280, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Compliance Title',
                'verbose_name_plural': 'Compliance Title',
            },
        ),
        migrations.CreateModel(
            name='CopyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Enter your website copy right text...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Copy Right Text')),
            ],
            options={
                'verbose_name': 'Copy-Right',
                'verbose_name_plural': 'Copy-Right',
            },
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Upload your website favicon...', null=True, upload_to='favicon/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicon',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your website logo...', null=True, upload_to='logo/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Logo')),
                ('alt_text', models.CharField(blank=True, help_text='Enter your logo alt text...', max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Logo ALT Text')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='NotFoundContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Upload your website not found image...', upload_to='not-found/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your website not found title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your website not found description...', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Not Found',
                'verbose_name_plural': 'Not Found',
            },
        ),
        migrations.CreateModel(
            name='ScheduleACall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Schedule A Call',
                'verbose_name_plural': 'Schedule A Call',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, help_text='Enter your website socail icon name...', null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Socail Icon')),
                ('url', models.URLField(blank=True, help_text='Enter your website socail link url...', max_length=280, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Socail Link URL')),
            ],
            options={
                'verbose_name': 'Social-Link',
                'verbose_name_plural': 'Social-Link',
            },
        ),
        migrations.CreateModel(
            name='StayCompliant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='stay-compliant/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('btn_name', models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Stay Compliant',
                'verbose_name_plural': 'Stay Compliant',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Address', max_length=280, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribe',
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='compliance/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('item_list', models.ManyToManyField(related_name='items', to='configuration.complianceitemlist')),
            ],
            options={
                'verbose_name': 'Compliance Items',
                'verbose_name_plural': 'Compliance Items',
            },
        ),
    ]