# Generated by Django 5.2.7 on 2026-01-08 21:17

import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='icon',
            field=models.FileField(blank=True, help_text='Upload your website favicon...', null=True, upload_to='favicon/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your website logo...', null=True, upload_to='logo/', validators=[utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Logo'),
        ),
    ]
