# Generated by Django 6.0.1 on 2026-02-02 09:24

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceitem',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='notfoundcontent',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Alt'),
        ),
        migrations.AddField(
            model_name='staycompliant',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Alt'),
        ),
        migrations.AlterField(
            model_name='complianceitem',
            name='item_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='configuration.complianceitemlist'),
        ),
        migrations.AlterField(
            model_name='complianceitem',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='compliancetitle',
            name='btn_name',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name'),
        ),
        migrations.AlterField(
            model_name='notfoundcontent',
            name='description',
            field=models.TextField(blank=True, help_text='Enter your website not found description...', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='notfoundcontent',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your website not found image...', null=True, upload_to='not-found/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='notfoundcontent',
            name='title',
            field=models.CharField(blank=True, help_text='Enter your website not found title...', max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='staycompliant',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
    ]
