# Generated by Django 5.2.7 on 2025-11-15 04:55

import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_contactinfo_delete_paymentlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your website not found image...', upload_to='not-found/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your website not found title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your website not found description...', verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
