# Generated by Django 5.2.7 on 2025-11-19 06:36

import django.db.models.deletion
import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_notfoundcontent_delete_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Compliance-Item-List',
                'verbose_name_plural': 'Compliance-Item-List',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('btn_name', models.CharField(max_length=280, verbose_name='Button Name')),
                ('btn_url', models.URLField(verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Compliance-Title',
                'verbose_name_plural': 'Compliance-Title',
            },
        ),
        migrations.CreateModel(
            name='StayCompliant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stay-compliant/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Stay-Compliant',
                'verbose_name_plural': 'Stay-Compliant',
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='compliance/', verbose_name='Image')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configuration.complianceitemlist')),
            ],
            options={
                'verbose_name': 'Compliance-Item',
                'verbose_name_plural': 'Compliance-Item',
            },
        ),
    ]
