# Generated by Django 5.2.7 on 2025-11-19 06:40

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_complianceitemlist_compliancetitle_staycompliant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staycompliant',
            name='image',
            field=models.FileField(upload_to='stay-compliant/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
