# Generated by Django 5.2.7 on 2025-11-19 09:30

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_staycompliant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceitem',
            name='image',
            field=models.FileField(upload_to='compliance/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='compliancetitle',
            name='btn_url',
            field=models.URLField(blank=True, null=True, verbose_name='Button URL'),
        ),
    ]
