# Generated by Django 5.2.7 on 2025-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_complianceitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceitem',
            name='item_list',
        ),
        migrations.AddField(
            model_name='complianceitem',
            name='item_list',
            field=models.ManyToManyField(related_name='items', to='configuration.complianceitemlist'),
        ),
    ]
