# Generated by Django 5.2.7 on 2025-11-26 06:04

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_remove_complianceitem_item_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(blank=True, help_text='Enter your website socail icon name...', null=True, upload_to='', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Socail Icon'),
        ),
    ]
