# Generated by Django 5.2.7 on 2025-11-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_remove_sociallink_name_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Address', max_length=280, verbose_name='Email')),
            ],
        ),
    ]
