# Generated by Django 5.2.7 on 2025-12-02 06:09

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleACall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number')),
            ],
        ),
        migrations.AlterField(
            model_name='notfoundcontent',
            name='image',
            field=models.FileField(help_text='Upload your website not found image...', upload_to='not-found/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
