# ==========================================
"""
HOMEPAGE ALL ROUTES
"""
# ==========================================
from django.urls import path
from api.homepage.views.homepage import (
    BannerViewSet,
    PaymnetInfoViewSet,
    SecurityFirmViewSet, 
    CybersecuritySolutionTitleViewSet, 
    CybersecuritySolutionItemViewSet,
    OurProvenProcessSecurityViewSet,
    OurProvenProcessSecurityItemsViewSet,
    ReviewViewSet,
    ReviewTopBarViewSet,
    ExperienceEicViewSet,
    ExperienceEicItemViewSet,
    GloballyAccreditedViewSet,
)

urlpatterns = [
    path(
        'banner/',
        BannerViewSet.as_view(),
        name='homepage_banner',
    ),
    path(
        'paymnet-info/',
        PaymnetInfoViewSet.as_view(),
        name='homepage_paymnet_info',
    ),
    path(
        'security-firm/',
        SecurityFirmViewSet.as_view(),
        name='homepage_security_firm',
    ),
    path(
        'cyber-security-solution-title/',
        CybersecuritySolutionTitleViewSet.as_view(),
        name='homepage_cyber_security_solution_title',
    ),
    path(
        'cyber-security-solution-items/',
        CybersecuritySolutionItemViewSet.as_view(),
        name='homepage_cyber_security_solution_items',
    ),
    path(
        'our-proven-process-security/',
        OurProvenProcessSecurityViewSet.as_view(),
        name='homepage_our_proven_process_security',
    ),
    path(
        'our-proven-process-security-items/',
        OurProvenProcessSecurityItemsViewSet.as_view(),
        name='homepage_our_proven_process_security_items',
    ),
    path(
        'review-top-bar/',
        ReviewTopBarViewSet.as_view(),
        name='homepage_review_top_bar',
    ),
    path(
        'review-items/',
        ReviewViewSet.as_view(),
        name='homepage_review_items',
    ),
    path(
        'experience-eic/',
        ExperienceEicViewSet.as_view(),
        name='homepage_experience_eic',
    ),
    path(
        'experience-eic-item/',
        ExperienceEicItemViewSet.as_view(),
        name='homepage_experience_eic_item',
    ),
    path(
        'globally-accredited/',
        GloballyAccreditedViewSet.as_view(),
        name='homepage_globally_accredited',
    ),
]
