# Generated by Django 5.2.7 on 2025-12-02 06:26

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context')),
                ('type', models.CharField(default='ServicePage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name')),
                ('url', models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('logo', models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Schema',
                'verbose_name_plural': 'SEO Schema',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tag',
            },
        ),
        migrations.CreateModel(
            name='ServicePageTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your service page top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your service page top bar description...', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Page Top Bar',
                'verbose_name_plural': 'Service Page Top Bar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Upload your service image...', upload_to='services/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your service title...', max_length=280, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Enter your service description...', null=True, verbose_name='Description')),
                ('seo_title', models.CharField(blank=True, help_text='Custom title for this blog detail page (for browser tab & search engines).', max_length=380, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, help_text='Short description for this blog (SEO meta description).', null=True, verbose_name='Meta Description')),
                ('seo_keywords', models.TextField(blank=True, help_text='Comma separated keywords for this blog.', null=True, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title for Facebook / LinkedIn when this blog is shared.', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph.', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Full URL of image for OG (optional).', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image for this blog. If set, this will be used.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_type', models.CharField(default='article', help_text='Type of Open Graph object, e.g., article.', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter card preview.', null=True, verbose_name='Twitter Image URL')),
                ('schema_type', models.CharField(blank=True, default='BlogPosting', help_text='JSON-LD @type, e.g., BlogPosting, Article, NewsArticle.', max_length=50, null=True, verbose_name='Schema Type')),
                ('schema_context', models.CharField(blank=True, default='https://schema.org', help_text='Usually https://schema.org', max_length=280, null=True, verbose_name='Schema Context')),
                ('schema_custom_json', models.TextField(blank=True, help_text='Optional: paste full JSON-LD here to override auto-generated schema.', null=True, verbose_name='Custom Schema JSON')),
                ('categories', models.ManyToManyField(related_name='services', to='services.categories', verbose_name='Service Categories')),
            ],
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter your FAQ question...', max_length=280, verbose_name='Question')),
                ('answer', models.TextField(help_text='Enter your FAQ answer...', verbose_name='Answer')),
                ('service', models.ForeignKey(blank=True, help_text='Select the service this FAQ item belongs to...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your FAQ title...', max_length=280, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='FAQ Title')),
                ('image', models.FileField(blank=True, null=True, upload_to='faq/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='FAQ File')),
                ('service', models.ForeignKey(blank=True, help_text='Select the service this FAQ belongs to...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Upload your service item image...', null=True, upload_to='services', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(help_text='Enter your service title...', max_length=280, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Enter your service description...', null=True, verbose_name='Description')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_title', models.CharField(blank=True, help_text='Enter your service main normal title...', max_length=280, null=True, verbose_name='Normal Title')),
                ('span_title', models.CharField(blank=True, help_text='Enter your service main normal span title...', max_length=280, null=True, verbose_name='Span Title')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_item', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePaymnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='services/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Paymnet Image')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('btn_name', models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesIncludeBottomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_bottom_items', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesIncludeBottomTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_bottom_title', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesIncludeTopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='services-include-top/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_top_items', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesIncludeTopTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_top_title', to='services.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter service item why choose us item name...', max_length=280, verbose_name='Name')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_why_choose_us_item', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceWhyChooseUsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, default='Default Title', max_length=280, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('image', models.FileField(blank=True, null=True, upload_to='services/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_why_choose_us_title', to='services.service')),
            ],
        ),
    ]
