# Generated by Django 5.2.7 on 2026-01-08 21:17

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesincludebottomitem',
            options={'verbose_name': 'Services Include Top Item', 'verbose_name_plural': 'Services Include Top Item'},
        ),
        migrations.AlterModelOptions(
            name='servicesincludebottomtitle',
            options={'verbose_name': 'Services Include Top Title', 'verbose_name_plural': 'Services Include Top Title'},
        ),
        migrations.AlterModelOptions(
            name='servicesincludetopitem',
            options={'verbose_name': 'Services Include Bottom Item', 'verbose_name_plural': 'Services Include Bottom Item'},
        ),
        migrations.AlterModelOptions(
            name='servicesincludetoptitle',
            options={'verbose_name': 'Services Include Bottom Title', 'verbose_name_plural': 'Services Include Bottom Title'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(blank=True, help_text='Enter your FAQ title...', max_length=280, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='FAQ Title'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter your FAQ answer...', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='servicesincludebottomitem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicesincludebottomitem',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='servicesincludebottomtitle',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicesincludebottomtitle',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='servicesincludetopitem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicesincludetopitem',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='servicesincludetoptitle',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicesincludetoptitle',
            name='title',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='compliance/', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=280, null=True, verbose_name='Title')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_compliance_item', to='services.service')),
            ],
            options={
                'verbose_name': 'Compliance Item',
                'verbose_name_plural': 'Compliance Items',
            },
        ),
        migrations.CreateModel(
            name='ComplianceItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280, verbose_name='Description')),
                ('items', models.ManyToManyField(blank=True, related_name='lists', to='services.complianceitem', verbose_name='Compliance Items')),
            ],
            options={
                'verbose_name': 'Compliance Item List',
                'verbose_name_plural': 'Compliance Lists',
            },
        ),
        migrations.CreateModel(
            name='ComplianceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title before span')),
                ('title_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title span')),
                ('title_after_span', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title after span')),
                ('btn_name', models.CharField(max_length=280, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_compliance_title', to='services.service')),
            ],
            options={
                'verbose_name': 'Compliance Title',
                'verbose_name_plural': 'Compliance Title',
            },
        ),
    ]
