# Generated by Django 5.2.7 on 2026-01-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('logo', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePageSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.RemoveField(
            model_name='service',
            name='schema_context',
        ),
        migrations.RemoveField(
            model_name='service',
            name='schema_custom_json',
        ),
        migrations.RemoveField(
            model_name='service',
            name='schema_type',
        ),
        migrations.AddField(
            model_name='seotag',
            name='author',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seotag',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='og_locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='schema_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_author',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='title',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='og_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='twitter_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='servicepage_schema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='services.servicepageschema'),
        ),
    ]
