# Generated by Django 5.2.7 on 2025-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='services.categories', verbose_name='Service Categories'),
        ),
    ]
