# Generated by Django 5.2.7 on 2025-11-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Select the service this FAQ belongs to...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service', verbose_name='Service'),
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='faq',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='faq',
            field=models.ManyToManyField(help_text='Select the FAQ this item belongs to...', related_name='faq_items', to='services.faq', verbose_name='Faq'),
        ),
    ]
