# Generated by Django 5.2.7 on 2025-11-19 13:26

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_faq_service_remove_faqitem_faq_faqitem_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.FileField(upload_to='faq/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='File'),
        ),
    ]
