# Generated by Django 5.2.7 on 2025-11-19 13:37

import django.core.validators
import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_faq_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='faq',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Select the service this FAQ item belongs to...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.FileField(upload_to='faq/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='FAQ File'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(help_text='Enter your FAQ title...', max_length=280, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='FAQ Title'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(help_text='Enter your FAQ answer...', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(help_text='Enter your FAQ question...', max_length=280, verbose_name='Question'),
        ),
    ]
