# Generated by Django 5.2.7 on 2025-11-20 04:03

import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_faqitem_faq_faqitem_service_alter_faq_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='serviceitemmain',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_item', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='image',
            field=models.FileField(help_text='Upload your service item image...', upload_to='services', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
