# Generated by Django 5.2.7 on 2025-11-20 04:35

import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceitem_service_serviceitemmain_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesincludetopitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_top_items', to='services.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicesincludetoptitle',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_top_title', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicesincludetopitem',
            name='image',
            field=models.FileField(upload_to='services-include-top/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
