# Generated by Django 5.2.7 on 2025-11-24 04:47

import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicesincludetopitem_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesincludebottomitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_bottom_items', to='services.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicesincludebottomtitle',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='include_bottom_title', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicesincludebottomitem',
            name='image',
            field=models.FileField(upload_to='services-include-top/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
