# Generated by Django 5.2.7 on 2025-11-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicesincludebottomitem_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesincludebottomitem',
            name='image',
        ),
    ]
