# Generated by Django 5.2.7 on 2025-11-26 08:57

import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_servicesincludebottomitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaymnet',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymnet_info', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicepaymnet',
            name='image',
            field=models.FileField(upload_to='services/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Paymnet Image'),
        ),
    ]
