# Generated by Django 5.2.7 on 2025-11-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicepaymnet_service_alter_servicepaymnet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepaymnet',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='services.service'),
        ),
    ]
