# Generated by Django 5.2.7 on 2025-11-26 09:16

import django.db.models.deletion
import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_servicepaymnet_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicewhychooseusitem',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_why_choose_us_item', to='services.service'),
        ),
        migrations.AddField(
            model_name='servicewhychooseustitle',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_why_choose_us_title', to='services.service'),
        ),
        migrations.AlterField(
            model_name='servicewhychooseusitem',
            name='name',
            field=models.CharField(help_text='Enter service item why choose us item name...', max_length=280, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicewhychooseustitle',
            name='image',
            field=models.FileField(upload_to='services/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
