# Generated by Django 5.2.7 on 2025-11-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicewhychooseusitem_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicewhychooseusitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_why_choose_us_item', to='services.service'),
        ),
    ]
