import type { Metadata } from "next";
import "./globals.css";
import {
  DM_Sans,
  Inter,
  Lexend,
  Poppins,
  Roboto,
  Space_Grotesk,
} from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import ScrollTopBottom from "@/components/scroll/scrollTopBottom";
import { getFetchData } from "@/utils/getFetchData";

const fetchSeoTag = async () => {
    const res = await getFetchData('/homepage/seo-tag/');
    return res?.data || null;
};

export async function generateMetadata(): Promise<Metadata> {
  try {
    return {
      title: "Eic - Home Page",
      description: "Generated by create next app",
      icons: {
        icon: "/images/eic-logo.svg",
      },
    };
  } catch (error) {
    console.error("Favicon fetch error:", error);
    return {
      title: "Eic - Home Page",
      icons: {
        icon: "/images/eic-logo.svg",
      },
    };
  }
}

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dmsans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-lexend",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-spacegrotesk",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`
        ${dmSans.variable}
        ${inter.variable}
        ${poppins.variable}
        ${roboto.variable}
        ${lexend.variable}
        ${spaceGrotesk.variable}
      `}
    >
      <body suppressHydrationWarning={true}>
        <ScrollTopBottom />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
