import type { Metadata } from "next";
import "./globals.css";
import {
  DM_Sans,
  Inter,
  Lexend,
  Poppins,
  Roboto,
  Space_Grotesk,
} from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { DOMAIN_NAME, MEDIA_URL } from "@/utils/api";
import { getFetchData } from "@/utils/getFetchData";

export async function generateMetadata(): Promise<Metadata> {
  try {
    const faviconData = await getFetchData('/configuration/favicon/');
    const faviconUrl = faviconData?.icon ? `${MEDIA_URL}${faviconData.icon}` : "../public/images/eic-logo.svg";

    return {
      viewport: {
        width: "device-width",
        initialScale: 1,
      },
      title: "Eic",
      description: "Generated by create next app",
      alternates: {
        canonical: `${DOMAIN_NAME}`,
      },
      icons: {
        icon: faviconUrl,
        shortcut: faviconUrl,
        apple: faviconUrl,
      },
      other: {
        "X-UA-Compatible": "IE=edge",
        robots: "index, follow",
        googlebot: "index, follow",
        bingbot: "index, follow",
      },
    };
  } catch (error) {
    console.error("Favicon fetch error:", error);
    return {
      title: "Eic",
      icons: {
        icon: "../public/images/eic-logo.svg",
      },
    };
  }
}

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dmsans",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-lexend",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-spacegrotesk",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`
        ${dmSans.variable}
        ${inter.variable}
        ${poppins.variable}
        ${roboto.variable}
        ${lexend.variable}
        ${spaceGrotesk.variable}
      `}
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
