# Generated by Django 5.2.7 on 2025-11-15 05:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter the privacy policy content here...', verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicyTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter privacy policy title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter privacy policy description...', verbose_name='Description')),
            ],
        ),
    ]
