# Generated by Django 5.2.7 on 2025-11-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicycontent',
            options={'verbose_name': 'Privacy Policy Content', 'verbose_name_plural': 'Privacy Policy Content'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicytopbar',
            options={'verbose_name': 'Privacy Policy Top Bar', 'verbose_name_plural': 'Privacy Policy Top Bar'},
        ),
    ]
