# Generated by Django 5.2.7 on 2025-11-15 09:13

import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConatctInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(help_text='Enter your website contact email...', max_length=280, verbose_name='Email')),
                ('address', models.CharField(help_text='Enter your website address...', max_length=280, verbose_name='Address')),
                ('phone_number1', models.CharField(help_text='Enter your number...', max_length=20, verbose_name='Number')),
                ('phone_number2', models.CharField(help_text='Enter your number...', max_length=20, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name...', max_length=280, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter your email address...', max_length=280, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Enter your phone number...', max_length=20, verbose_name='Phone Number')),
                ('company_name', models.CharField(help_text='Enter your compnay name...', max_length=280, verbose_name='Company Name')),
                ('message', models.TextField(help_text='Enter your message', verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your contact top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your top bar description...', verbose_name='Description')),
                ('image', models.ImageField(help_text='Upload your contact image...', upload_to='contact/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enter your google map url...', verbose_name='Google Map URL')),
            ],
        ),
    ]
