# Generated by Django 5.2.7 on 2025-12-02 06:26

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConatctInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(help_text='Enter your website contact email...', max_length=280, verbose_name='Email')),
                ('address', models.CharField(help_text='Enter your website address...', max_length=280, verbose_name='Address')),
                ('phone_number1', models.CharField(help_text='Enter your number...', max_length=20, verbose_name='Number')),
                ('phone_number2', models.CharField(help_text='Enter your number...', max_length=20, verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Conatct Infomation',
                'verbose_name_plural': 'Conatct Infomation',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name...', max_length=280, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter your email address...', max_length=280, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Enter your phone number...', max_length=20, verbose_name='Phone Number')),
                ('company_name', models.CharField(help_text='Enter your compnay name...', max_length=280, verbose_name='Company Name')),
                ('message', models.TextField(help_text='Enter your message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
            },
        ),
        migrations.CreateModel(
            name='ContactTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your contact top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your top bar description...', verbose_name='Description')),
                ('image', models.FileField(help_text='Upload your contact image...', upload_to='contact/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Contact Top Bar',
                'verbose_name_plural': 'Contact Top Bar',
            },
        ),
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enter your google map url...', max_length=800, verbose_name='Google Map URL')),
            ],
            options={
                'verbose_name': 'Google Map',
                'verbose_name_plural': 'Google Map',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context')),
                ('type', models.CharField(default='ContactPage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name')),
                ('url', models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('logo', models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL')),
                ('address', models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Schema',
                'verbose_name_plural': 'SEO Schema',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title')),
                ('description', models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_image_file', models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Tag',
                'verbose_name_plural': 'SEO Tag',
            },
        ),
    ]
