# Generated by Django 5.2.7 on 2025-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemap',
            name='url',
            field=models.URLField(help_text='Enter your google map url...', max_length=800, verbose_name='Google Map URL'),
        ),
    ]
