# Generated by Django 5.2.7 on 2025-11-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_googlemap_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conatctinfomation',
            options={'verbose_name': 'Conatct Infomation', 'verbose_name_plural': 'Conatct Infomation'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Form'},
        ),
        migrations.AlterModelOptions(
            name='contacttopbar',
            options={'verbose_name': 'Contact Top Bar', 'verbose_name_plural': 'Contact Top Bar'},
        ),
        migrations.AlterModelOptions(
            name='googlemap',
            options={'verbose_name': 'Google Map', 'verbose_name_plural': 'Google Map'},
        ),
    ]
