# Generated by Django 5.2.7 on 2025-11-24 13:12

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_conatctinfomation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttopbar',
            name='image',
            field=models.FileField(help_text='Upload your contact image...', upload_to='contact/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
