# Generated by Django 5.2.7 on 2025-12-02 06:09

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_schema_seotag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'verbose_name': 'SEO Schema', 'verbose_name_plural': 'SEO Schema'},
        ),
        migrations.AlterModelOptions(
            name='seotag',
            options={'verbose_name': 'SEO Tag', 'verbose_name_plural': 'SEO Tag'},
        ),
        migrations.AddField(
            model_name='schema',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address for local business schema.', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='schema',
            name='logo',
            field=models.URLField(blank=True, help_text='Logo URL for schema.org (recommended).', null=True, verbose_name='Logo URL'),
        ),
        migrations.AddField(
            model_name='seotag',
            name='og_image_file',
            field=models.ImageField(blank=True, help_text='Upload OG image instead of or in addition to URL.', null=True, upload_to='seo/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='OG Image File'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='contact_type',
            field=models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=280, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='context',
            field=models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=280, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='description',
            field=models.TextField(blank=True, help_text='Page description for schema.org.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address.', max_length=280, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(blank=True, help_text='The name/title of the page.', max_length=255, null=True, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='url',
            field=models.URLField(blank=True, help_text='Full URL of the page.', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the page for SEO purposes.', null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seotag',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the page for search engines and browser tab.', max_length=380, null=True, verbose_name='SEO Title'),
        ),
    ]
