# Generated by Django 5.2.7 on 2025-11-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsconditioncontent',
            options={'verbose_name': 'Terms Condition Content', 'verbose_name_plural': 'Terms Condition Content'},
        ),
        migrations.AlterModelOptions(
            name='termsconditiontopbar',
            options={'verbose_name': 'Terms Condition Top Bar', 'verbose_name_plural': 'Terms Condition Top Bar'},
        ),
    ]
