export const DOMAIN_NAME=process.env.NEXT_PUBLIC_DOMAIN_NAME;
export const MEDIA_URL=process.env.NEXT_PUBLIC_MEDIA_URL;
export const SERVER_URL=process.env.NEXT_PUBLIC_SERVER_URL;
export const REVALIDATE_SECRET=process.env.NEXT_PUBLIC_REVALIDATE_SECRET;
export const FRONTEND_API_KEY=process.env.NEXT_PUBLIC_FRONTEND_API_KEY;
