# Generated by Django 5.2.7 on 2025-12-02 06:26

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_before_span', models.CharField(blank=True, help_text='Upload your feature title before span...', max_length=255, null=True, verbose_name='Feature title before span')),
                ('title_span', models.CharField(blank=True, help_text='Upload your feature title span...', max_length=255, null=True, verbose_name='Feature title span')),
                ('title_after_span', models.CharField(blank=True, help_text='Upload your feature title after span...', max_length=255, null=True, verbose_name='Feature title after span')),
                ('features_btn_name', models.CharField(blank=True, max_length=180, null=True, verbose_name='Features Button Name')),
                ('features_btn_url', models.URLField(blank=True, max_length=180, null=True, verbose_name='Features Button URL')),
            ],
            options={
                'verbose_name': 'Feature Top Bar',
                'verbose_name_plural': 'Feature Top Bar',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, help_text='Upload your feature image...', null=True, upload_to='features/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Feature Image')),
                ('bg', models.FileField(blank=True, help_text='Upload your feature bg image...', null=True, upload_to='features/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Feature BG Image')),
                ('name', models.CharField(help_text='Enter your feature name...', max_length=280, unique=True, verbose_name='Feature Name')),
                ('slug', models.SlugField(editable=False, max_length=280, unique=True, verbose_name='Feature Slug')),
                ('description', models.TextField(blank=True, help_text='Enter your feature description...', null=True, verbose_name='Feature Description')),
                ('brn_name', models.CharField(blank=True, max_length=280, null=True, verbose_name='Button Name')),
                ('btn_url', models.URLField(blank=True, null=True, verbose_name='Button URL')),
            ],
            options={
                'verbose_name': 'Feature-Item',
                'verbose_name_plural': 'Feature-Item',
            },
        ),
    ]
