# Generated by Django 5.2.7 on 2025-11-19 10:02

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature Top Bar', 'verbose_name_plural': 'Feature Top Bar'},
        ),
        migrations.AlterModelOptions(
            name='featureitem',
            options={'verbose_name': 'Feature-Item', 'verbose_name_plural': 'Feature-Item'},
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='bg',
            field=models.FileField(blank=True, help_text='Upload your feature bg image...', null=True, upload_to='features/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Feature BG Image'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your feature image...', null=True, upload_to='features/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Feature Image'),
        ),
    ]
