# Generated by Django 6.0.1 on 2026-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureitem',
            name='slug',
        ),
        migrations.AddField(
            model_name='featureitem',
            name='alt',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Image Alt Text'),
        ),
    ]
