# Generated by Django 5.2.7 on 2025-11-19 02:05

import ckeditor_uploader.fields
import utils.validate_image_extension
import utils.validate_image_size
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStorieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStorieTopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your success stories top bar title...', max_length=280, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter your success stories description...', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Success Stories Top Bar',
                'verbose_name_plural': 'Success Stories Top Bar',
            },
        ),
        migrations.CreateModel(
            name='SuccessStorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload your success story main image...', null=True, upload_to='success-stories/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION, utils.validate_image_size.VALIDATE_IMAGE_SIZE], verbose_name='Image')),
                ('title', models.CharField(max_length=280, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('budget_description', models.TextField(verbose_name='Budget Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('client_name', models.CharField(blank=True, max_length=280, null=True, verbose_name='Client Name')),
                ('subject', models.CharField(blank=True, max_length=280, null=True, verbose_name='Subject')),
                ('budget', models.CharField(blank=True, max_length=280, null=True, verbose_name='Budget')),
                ('duration', models.CharField(blank=True, max_length=280, null=True, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='success_stories', to='success_stories.successstoriecategory', verbose_name='Categories')),
            ],
        ),
    ]
