# Generated by Django 5.2.7 on 2025-11-25 11:53

import utils.validate_image_extension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='https://schema.org', help_text='Always https://schema.org', max_length=255, verbose_name='Context')),
                ('type', models.CharField(default='ContactPage', help_text='@type for JSON-LD', max_length=50, verbose_name='Type')),
                ('name', models.CharField(help_text='The name/title of the page.', max_length=255, verbose_name='Page Name')),
                ('url', models.URLField(help_text='Full URL of the page.', verbose_name='URL')),
                ('description', models.TextField(help_text='Page description for schema.org.', verbose_name='Description')),
                ('contact_type', models.CharField(blank=True, help_text='contactType for schema.org, e.g., Customer Support.', max_length=100, null=True, verbose_name='Contact Type')),
                ('email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=50, null=True, verbose_name='Phone Number')),
                ('same_as_facebook', models.URLField(blank=True, help_text='URL to Facebook profile or page.', null=True, verbose_name='Facebook Profile')),
                ('same_as_instagram', models.URLField(blank=True, help_text='URL to Instagram profile.', null=True, verbose_name='Instagram Profile')),
                ('same_as_linkedin', models.URLField(blank=True, help_text='URL to LinkedIn profile.', null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the page for search engines and browser tab.', max_length=255, verbose_name='SEO Title')),
                ('description', models.TextField(help_text='A short description of the page for SEO purposes.', verbose_name='Meta Description')),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for SEO.', null=True, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title for Open Graph (Facebook, LinkedIn).', max_length=255, null=True, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Description for Open Graph (Facebook, LinkedIn).', null=True, verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, help_text='Image URL for Open Graph preview.', null=True, verbose_name='OG Image URL')),
                ('og_url', models.URLField(blank=True, help_text='Canonical URL for Open Graph.', null=True, verbose_name='OG URL')),
                ('og_type', models.CharField(default='website', help_text='Type of Open Graph object. Default is "website".', max_length=50, verbose_name='OG Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Title for Twitter Card.', max_length=255, null=True, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Description for Twitter Card.', null=True, verbose_name='Twitter Description')),
                ('twitter_image', models.URLField(blank=True, help_text='Image URL for Twitter Card preview.', null=True, verbose_name='Twitter Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='successstorie',
            name='image',
            field=models.FileField(blank=True, help_text='Upload your success story main image...', null=True, upload_to='success-stories/', validators=[utils.validate_image_extension.VALIDATE_IMAGE_EXTENSION], verbose_name='Image'),
        ),
    ]
